apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: productcatalogservice
    spec:
      template:
        spec:
          containers:
            - name: server
              resources:
                requests:
                  cpu: 100m
                  memory: 128Gi
                limits:
                  cpu: 200m
                  memory: 128Gi
