apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: productcatalogservice
    spec:
      template:
        spec:
          nodeSelector:
            disktype: ssd
